
import { FetchApi } from "@/constants/FetchApi";
import { configBase } from "@/constants/constants";
//import feed from './feed.json';

const FetchData = async (config: any) => {
  return await FetchApi(config.apiPath + config.endPointPath.sitemapDoc + 20);
};
const sitemap= async (req:any, res:any) => {
  const _domain=req.headers.host;
    // console.log("_domain",_domain);
     let domain='_';
     let config_base= configBase["_"];
     if(!_domain.includes('localhost')){
       domain=domain+_domain.replace('www.','').replace('-','').replace('.','');
       config_base= configBase[domain];
     }
     let config = config_base?.SelectMangaTypeByPage("");

    let xmlresult:any = [];
    if (config_base?.ActMangaSource !== undefined && config_base?.ActMangaSource !== null) 
    {
    for (const item of config_base?.ActMangaSource) {
      config = config_base?.SelectMangaTypeByPage(item.value);
      let _data = await FetchData(config);
      //console.log("server-sitemap", _data);
      let fields = _data?.map((item: any) => {
        const url = `${config.configPrefix.url_host}${config.configPrefix.pageManga}/${config.configPrefix.startManga}${item.idDoc}${config.configPrefix.endManga}`;
        return ` <li class="lpage">
        <a href="${url}" title="${item.name}">${item.name}</a>
        </li>`;
      });
      const rend_manga = `<ul class="level-2">
              <li class="lhead">${
                item.lable
              } <span class="lcount">20 Item New Update</span></li>
            ${fields.join("")}
          </ul>`;
      xmlresult = xmlresult.concat(rend_manga);
    }
  }
    // Add urlSet to entire sitemap string

    const sitemap = `<!doctype html>
    <html lang="en">
    
    <head>
      <meta charset="utf-8" />
      <title>${config?.configSetting?.lbl_domain_Page} Site Map - Generated by www.xml-sitemaps.com</title>
      <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
      <style type="text/css">
      body {
        background-color: #fff;
        font-family: "Roboto", "Helvetica", "Arial", sans-serif;
        margin: 0;
      }
    
      #top {
    
        background-color: #b1d1e8;
        font-size: 16px;
        padding-bottom: 40px;
      }
    
      nav {
        font-size: 24px;
    
        margin: 0px 30px 0px;
        border-bottom-left-radius: 6px;
        border-bottom-right-radius: 6px;
        background-color: #f3f3f3;
        color: #666;
        box-shadow: 0 10px 20px -12px rgba(0, 0, 0, 0.42), 0 3px 20px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
        padding: 10px 0;
        text-align: center;
        z-index: 1;
      }
    
      h3 {
        margin: auto;
        padding: 10px;
        max-width: 600px;
        color: #666;
      }
    
      h3 span {
        float: right;
      }
    
      h3 a {
        font-weight: normal;
        display: block;
      }
    
    
      #cont {
        position: relative;
        border-radius: 6px;
        box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
    
        background: #f3f3f3;
    
        margin: -20px 30px 0px 30px;
        padding: 20px;
      }
    
      a:link,
      a:visited {
        color: #0180AF;
        text-decoration: underline;
      }
    
      a:hover {
        color: #666;
      }
    
    
      #footer {
        padding: 10px;
        text-align: center;
      }
    
      ul {
          margin: 0px;
    
          padding: 0px;
          list-style: none;
      }
      li {
        margin: 0px;
      }
      li ul {
        margin-left: 20px;
      }
    
      .lhead {
        background: #ddd;
        padding: 10px;
          margin: 10px 0px;
      }
    
      .lcount {
        padding: 0px 10px;
      }
    
      .lpage {
        border-bottom: #ddd 1px solid;
        padding: 5px;
      }
      .last-page {
        border: none;
      }
      </style>
    </head>
    
    <body>
      <div id="top">
        <nav>${config?.configSetting?.lbl_domain_Page} HTML Site Map</nav>
        <h3>Last updated: 2022, September 5 ${config?.configSetting?.lbl_domain_Page} Homepage</h3>
      </div>
      <div id="cont">
        <ul class="level-0">
                <li class="lhead">https://${config?.configSetting?.lbl_domain_Page} </li>
                <li>
                ${xmlresult.join("")}
          </li>
        </ul>
      </div>
      <div id="footer">
        Copyright &copy; 2005-2022 
      </div>
    </body>
    
    </html>`;

    // set response content header to xml
    res.setHeader("Content-Type", "text/html");

    return res.status(200).send(sitemap);
}


export default sitemap;